"""ASGI compatibility entry point. HTTP implementation lives in api/."""
from .api.application import app
from .api.dependencies import clean_filename
from .api.dependencies import _clean_risk_payload
from .api.dependencies import serialize_document
from .api.lifecycle import lifespan
from .api.dependencies import SAMPLE_TEMPLATE_FILES
from .api.dependencies import _sample_template_root
from .api.schemas import ReportSectionUpdate
from .api.schemas import ReportGenerationRequest
from .api.schemas import LoginRequest
from .api.schemas import RegistrationRequest
from .api.schemas import AccountSettingsUpdate
from .api.schemas import PerformanceReviewRequest
from .api.schemas import ProjectAIUpdate
from .api.schemas import MenuPermissionsUpdate
from .api.schemas import ProjectCreateRequest
from .api.schemas import ProjectLocaleUpdate
from .api.dependencies import PUBLIC_API_PATHS
from .api.dependencies import ACCOUNT_ONLY_API_PATHS
from .api.dependencies import REPORT_API_PREFIX
from .api.middleware import account_scope
from .api.dependencies import _run_background_for_account
from .api.dependencies import _reserve_project_workflow
from .api.auth_routes import auth_login
from .api.auth_routes import auth_register
from .api.auth_routes import auth_me
from .api.dependencies import _request_account_id
from .api.dependencies import _request_llm_model
from .api.auth_routes import account_settings
from .api.auth_routes import save_account_settings
from .api.auth_routes import admin_ai_models
from .api.auth_routes import admin_project_ai
from .api.auth_routes import admin_accounts
from .api.auth_routes import admin_projects
from .api.auth_routes import admin_create_project
from .api.auth_routes import admin_account_menus
from .api.auth_routes import admin_account_login_history
from .api.project_routes import project_i18n
from .api.project_routes import project_i18n_locale
from .api.auth_routes import auth_logout
from .api.project_routes import healthz
from .api.project_routes import api_root
from .api.project_routes import dashboard
from .api.project_routes import project_overview
from .api.project_routes import pdm_monitoring
from .api.project_routes import pdm_refresh_status
from .api.project_routes import performance_analysis_plan
from .api.project_routes import refresh_pdm
from .api.intake_routes import taxonomy
from .api.intake_routes import get_foundation
from .api.intake_routes import upload_documents
from .api.intake_routes import list_jobs
from .api.intake_routes import get_job
from .api.intake_routes import download_original_document
from .api.intake_routes import download_sample_template
from .api.intake_routes import cancel_intake_job
from .api.schemas import IntakeModeRequest
from .api.intake_routes import set_intake_mode
from .api.intake_routes import retry_job
from .api.intake_routes import list_suggestions
from .api.intake_routes import list_document_slots
from .api.evaluation_routes import latest_evaluations
from .api.project_routes import localized_dashboard_and_project_overview
from .api.evaluation_routes import evaluation_status
from .api.schemas import DacReviewRequest
from .api.evaluation_routes import dac_analysis_plan
from .api.evaluation_routes import start_evaluation
from .api.dependencies import serialize_report_section
from .api.report_routes import list_report_sections
from .api.report_routes import report_job_tray
from .api.report_routes import get_report_reference_stats
from .api.report_routes import get_report_section
from .api.report_routes import update_report_section
from .api.report_routes import start_report_section_generation
from .api.report_routes import refresh_current_report
from .api.report_routes import start_all_report_generation
from .api.dependencies import serialize_generation_run
from .api.report_routes import latest_report_generation
from .api.report_routes import cancel_report_generation
from .api.report_routes import resume_report_generation
from .api.dependencies import serialize_report_export
from .api.report_routes import start_report_export
from .api.report_routes import latest_report_export
from .api.report_routes import latest_completed_report_export
from .api.report_routes import get_report_export
from .api.report_routes import download_report_export
from .api.report_routes import verify_report_rhwp_toc
from .api.dependencies import serialize_presentation_export
from .api.report_routes import start_presentation_export
from .api.report_routes import latest_presentation_export
from .api.report_routes import get_presentation_export
from .api.report_routes import download_presentation_export
from .api.intake_routes import approve_all_suggestions
from .api.intake_routes import approve_suggestion
