const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const root = path.resolve(__dirname, '../..');
const html = fs.readFileSync(path.join(root, '0821_OoooDaon_v1.0.html'), 'utf8');
const script = fs.readFileSync(path.join(root, 'assets/odaon-v1-live.js'), 'utf8');
const adminScript = fs.readFileSync(path.join(root, 'assets/service-admin-ui.js'), 'utf8');
const dockerIgnore = fs.readFileSync(path.join(root, '.dockerignore'), 'utf8');
const dockerfile = fs.readFileSync(path.join(root, 'redesign/frontend/Dockerfile'), 'utf8');
const nginx = fs.readFileSync(path.join(root, 'redesign/frontend/nginx.conf'), 'utf8');
for (const match of html.matchAll(/<script>([\s\S]*?)<\/script>/g)) new vm.Script(match[1]);
assert.ok(html.includes('main{flex:1;padding:22px 200px 110px;min-width:0}'), 'all menu pages must share the requested 200px horizontal gutters');
assert.ok(html.includes('main>.inner{width:100%;max-width:none;margin:0;min-width:0}'), 'the inner content cap must not add extra horizontal margins');
assert.ok(html.includes('body:not(.report-mode) main>.inner{container:workspace / inline-size}'), 'menu grids must respond to actual available content width');
assert.ok(html.includes('@container workspace (max-width:900px)'), 'narrow content must reflow without reducing the requested gutters');
const ids = ['aiGen', 'aiPrompt', 'reportSectionNav', 'reportAiNextStep', 'reportAiStatus', 'reportAiTarget', 'reportLifecycle',
  'reportQualityWarnings', 'reportAiTemplates', 'aiCheckStatus', 'adminCreateAccount', 'adminDetail', 'reportGenerationHistory'];
for (const id of ids) assert.equal(html.split(`id="${id}"`).length - 1, 1, `${id} must occur exactly once`);
assert.ok(!html.includes('id="reportEditor"'), 'manual content editor must be removed');
assert.ok(!html.includes('id="saveReportSection"'), 'manual save control must be removed');
assert.ok(!/\.repai\s*\{\s*display\s*:\s*none/.test(html), 'responsive view must not hide AI controls');
assert.ok(!/\.repai\s+\.optlist\s*\{\s*display\s*:\s*flex/.test(html), 'legacy cards must not push the AI form down');
assert.ok(html.includes('aria-live="polite"'));
for (const asset of ['report-section-flow.js', 'service-admin-ui.js']) {
  assert.ok(html.indexOf(`assets/${asset}`) < html.indexOf('assets/odaon-v1-live.js?'));
  assert.ok(dockerIgnore.includes(`!/assets/${asset}`), `${asset} must be allowed into Docker build context`);
  assert.ok(dockerfile.includes(asset), `${asset} must be verified during image build`);
}
assert.ok(dockerfile.includes('test -s /usr/share/nginx/html/assets/$module'));
assert.ok(nginx.includes('location /assets/ {'));
assert.ok(nginx.includes('try_files $uri $uri/ =404;'), 'missing JS must not be replaced with index.html');
assert.ok(html.includes('onerror="reportModuleUnavailable()"'));
assert.ok(script.includes('!window.ReportSectionFlow?.createFlow || !window.ReportSectionPreview?.create || !window.ServiceAdminUI?.create'));
assert.ok(html.includes('const PROJECTS=[];'));
assert.ok(!html.includes('PROJECTS.map('), 'sample project switcher must not be rendered');
assert.ok(!html.includes('FILES.push('), 'example file inventory must not be seeded');
const initialRender = html.split('/* Initial service shell:')[1].split('</script>')[0];
assert.ok(!initialRender.includes('renderPdm()'));
assert.ok(!initialRender.includes('renderSecs()'));
assert.ok(script.includes('reportInstructions.set(activeReportPart'));
assert.ok(script.includes('if (!reportFlow.isCurrent(id, readToken)) return;'));
assert.ok(script.includes("sectionPreview.select(id, section.content || '', section.title)"));
assert.ok(script.includes('document.hidden ? 10000 : 2500'));
assert.ok(script.includes('window.ReportSectionFlow.generationBlock'));
assert.ok(script.includes('Clear all in-memory report, evidence, evaluation and translation state.'));
assert.ok(script.includes('Date.now() - reportLifecycleCheckedAt < 12000'));
assert.ok(script.includes('if (!data.has_project && !data.account?.is_admin)'));
assert.ok(adminScript.includes('type="password"'));
assert.ok(!adminScript.includes('localStorage'));
assert.ok(!adminScript.includes('sessionStorage'));
const context = { window: {} };
vm.createContext(context);
vm.runInContext(adminScript, context);
const escapeHtml = (value) => String(value).replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('"', '&quot;');
const api = context.window.ServiceAdminUI.create({ request() {}, escapeHtml, refresh() {}, accounts() { return []; },
  projects() { return [{ id: 'one', name: '<script>test</script>' }, { id: 'two', name: '사업 2' }]; }, selected() {}, notify() {} });
const detail = api.detail({ id: 'u1', is_active: true, projects: [{ id: 'one' }] });
assert.ok(detail.includes('&lt;script>test&lt;/script>'), 'project names must be escaped');
assert.ok(detail.includes('data-member-project="one" checked'));
assert.ok(detail.includes('data-member-project="two" '));
assert.equal(api.detail({ is_admin: true }), '', 'regular account controls cannot modify system administrator');
assert.ok(detail.includes('자료를 삭제하지 않습니다'));
// Exercise the actual renderer with plain UI-state stubs (no browser or API).
const generationRenderer = script.slice(script.indexOf('  function renderGeneration(status) {'), script.indexOf('  async function pollGeneration()'));
const nodes = new Map();
const node = (id) => { if (!nodes.has(id)) nodes.set(id, { hidden: false, open: false, dataset: {}, style: {}, parentElement: {}, textContent: '' }); return nodes.get(id); };
const rendererContext = { window: {}, byId: node, reportSections: [], activeReportPart: null, renderSectionAssistant() {} };
vm.createContext(rendererContext);
vm.runInContext(generationRenderer, rendererContext);
const failedRun = Object.freeze({ status: 'failed', total_sections: 27, completed_sections: 13, failed_sections: 1, error_message: 'historical interruption' });
rendererContext.renderGeneration(failedRun);
assert.equal(node('reportGenerationHistory').open, false, 'failed history defaults to collapsed');
assert.equal(node('reportGenerationBar').parentElement.hidden, true, 'failed history has no progress bar');
assert.equal(node('reportGenerationPercent').hidden, true);
assert.ok(node('reportGenerationMessage').textContent.includes('historical interruption'), 'historical error must be retained');
node('reportGenerationHistory').open = true;
rendererContext.renderGeneration(failedRun);
assert.equal(node('reportGenerationHistory').open, true, 'user-opened historical details remain open');
rendererContext.renderGeneration(Object.freeze({ status: 'running', total_sections: 27, completed_sections: 3 }));
assert.equal(node('reportGenerationHistory').open, true, 'active work is expanded');
assert.equal(node('reportGenerationBar').parentElement.hidden, false);
rendererContext.renderGeneration(Object.freeze({ status: 'completed', total_sections: 27, completed_sections: 27 }));
assert.equal(node('reportGenerationHistory').open, false, 'finished work becomes collapsed history');
assert.equal(node('reportGenerationBar').parentElement.hidden, true);
console.log(JSON.stringify({ status: 'PASS', checkedIds: ids.length, tests: 'UI contract, responsiveness, dependency order, tenant transition, credential privacy, membership rendering' }));
