const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const source = fs.readFileSync('assets/app-controller.js','utf8');
const html = fs.readFileSync('frontend/index.html','utf8') + fs.readFileSync('assets/app-shell.js','utf8') + fs.readFileSync('assets/app-styles.css','utf8');
const admin = fs.readFileSync('assets/service-admin-ui.js','utf8');
const nodes = {adminUserSearch:{value:''},adminUserProject:{value:'p2'},adminAccountRows:{innerHTML:''}};
const context = {byId:id=>nodes[id],adminAccounts:[{id:'u1',username:'first',display_name:'하나',projects:[{id:'p1',name:'프로젝트1'}]},{id:'u2',username:'second',display_name:'둘',projects:[{id:'p2',name:'프로젝트2'}]}],selectedAdminAccountId:'u1',esc:String,formatAdminDate:()=>'-',renderAdminDetail(account){context.detailId=account?.id;}};
vm.createContext(context);
vm.runInContext(source.slice(source.indexOf('  function renderAdminRows()'),source.indexOf('  async function renderAdminDetail')),context);
context.renderAdminRows();
assert.equal(context.selectedAdminAccountId,'u2');
assert.equal(context.detailId,'u2','filter cannot retain another project user in detail actions');
nodes.adminUserSearch.value='no-matches'; context.renderAdminRows();
assert.equal(context.selectedAdminAccountId,null);
assert.equal(context.detailId,undefined);
assert(nodes.adminAccountRows.innerHTML.includes('조건에 맞는 사용자가 없습니다'));
assert(html.includes('window.KODAME_IS_ADMIN?gr.adminOnly:!gr.adminOnly'));
assert(html.includes('body.admin-mode #drawer'));
assert(source.includes("data.account?.is_admin ? '#/admin/projects'"));
assert(source.includes('data.has_project && !window.KODAME_IS_ADMIN'));
assert(admin.includes('project_id: data.get'));
assert(admin.includes('serviceConfirmDialog'));
assert(!admin.includes('root.confirm('));
console.log('PASS operator-only navigation, filtered account selection, empty details, atomic issuance UI and internal confirmation');
