const assert = require('node:assert/strict');
const { createRevisionGate } = require('../../assets/report-section-preview.js');
const gate = createRevisionGate();
const a = gate.update('working-factors', '원본');
assert(gate.accepts(a));
assert.equal(gate.update('working-factors', '원본'), null);
const b = gate.update('working-factors', '수정');
assert(!gate.accepts(a), 'late render of old text must be ignored');
assert(gate.accepts(b));
const c = gate.update('project-overview', '표 수정');
assert(!gate.accepts(b), 'late render of another section must be ignored');
assert(gate.accepts(c));
gate.invalidate();
assert(!gate.accepts(c), 'switch/reset invalidates pending render');
assert.equal(gate.current(), null);
const fs = require('node:fs');
const source = fs.readFileSync('assets/report-section-preview.js', 'utf8');
assert(source.includes("event.source !== frame.contentWindow"));
assert(source.includes('event.origin !== origin'));
assert(!source.includes("method: 'PUT'"), 'preview must never save');
assert(!source.includes('/generate'), 'preview must never invoke LLM');
assert(source.includes('await waitForFrame()'), 'iframe initial load must be bounded');
assert(source.includes('focused.setSelectionRange(...caret)'), 'rendering must preserve the editing caret');
const live = fs.readFileSync('assets/app-controller.js', 'utf8');
assert(live.includes('activeReportPart === selectedAtStart'), 'background refresh must not change a newer selection');
console.log('PASS: section preview revision gate + no writes/LLM + origin/source guards');
