const fs = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const close = {hidden:false};
const elements = {tray:{querySelector(){return close;},classList:{add(){this.open=true;},remove(){this.open=false;}}},trayJobs: {innerHTML:''}, trayLive: {classList:{toggle(_name,value){this.active=value;}}}};
const sandbox = {window:{}, document:{getElementById:id=>elements[id]}};
vm.runInNewContext(fs.readFileSync('assets/service-job-tray.js','utf8'), sandbox);
const tray = sandbox.window.ServiceJobTray;
tray.render(); assert.match(elements.trayJobs.innerHTML,/진행 중인 AI 작업이 없습니다/);
tray.update('dac',{name:'DAC',active:true,completed:2,total:6,detail:'<source>'});
assert.equal(elements.trayLive.classList.active,true);
assert.equal(elements.tray.classList.open,true);
assert.equal(close.hidden,true);
elements.tray.classList.remove('on');
tray.render();
assert.equal(elements.tray.classList.open,true);
assert.match(elements.trayJobs.innerHTML,/33%/);
assert.match(elements.trayJobs.innerHTML,/&lt;source&gt;/);
tray.update('dac',{name:'DAC',active:false,failed:true,detail:'검증 실패'});
assert.equal(elements.trayLive.classList.active,false);
assert.equal(close.hidden,false);
assert.match(elements.trayJobs.innerHTML,/실패/);
assert.doesNotMatch(elements.trayJobs.innerHTML,/>완료</);
tray.clear(); assert.match(elements.trayJobs.innerHTML,/작업이 없습니다/);
tray.update('report',{name:'보고서',active:false,cancelled:true,completed:13,total:27,detail:'사용자 중단'});
assert.match(elements.trayJobs.innerHTML,/>중단</);
assert.doesNotMatch(elements.trayJobs.innerHTML,/>완료</);
console.log('PASS actual job progress, failed state, escaping and clear');
tray.clear();
tray.syncIntake([{id:'old',status:'completed',file_name:'old.txt',progress:100}, {id:'new',status:'queued',stage:'queued',file_name:'<new>.txt',progress:0}]);
assert.doesNotMatch(elements.trayJobs.innerHTML,/old.txt/);
assert.match(elements.trayJobs.innerHTML,/&lt;new&gt;.txt/);
assert.match(elements.trayJobs.innerHTML,/분석 대기/);
assert.equal(elements.trayLive.classList.active,true);
tray.syncIntake([{id:'new',status:'processing',stage:'parsing',file_name:'new.txt',progress:15}]);
assert.match(elements.trayJobs.innerHTML,/텍스트를 추출/);
tray.syncIntake([{id:'new',status:'processing',stage:'analyzing',file_name:'new.txt',progress:68}]);
assert.match(elements.trayJobs.innerHTML,/매칭을 분석/);
assert.match(elements.trayJobs.innerHTML,/68%/);
tray.syncIntake([{id:'new',status:'waiting_llm',file_name:'new.txt',progress:45,error_message:'API 연결 확인'}]);
assert.match(elements.trayJobs.innerHTML,/AI 연결 대기/);
assert.match(elements.trayJobs.innerHTML,/API 연결 확인/);
assert.equal(elements.trayLive.classList.active,false);
tray.syncIntake([{id:'new',status:'completed',stage:'review',file_name:'new.txt',progress:100}]);
assert.match(elements.trayJobs.innerHTML,/분석 완료/);
tray.update('dac',{name:'DAC',active:true,detail:'평가 중'});
tray.syncIntake([]);
assert.doesNotMatch(elements.trayJobs.innerHTML,/new.txt/);
assert.match(elements.trayJobs.innerHTML,/DAC/);
tray.clear();
assert.doesNotMatch(elements.trayJobs.innerHTML,/new.txt/);
console.log('PASS restored intake queue, phases, wait/completion, deleted documents and project reset');
tray.syncIntake([{id:'later',file_name:'later.txt',status:'queued',queue_position:3}, {id:'now',file_name:'now.txt',status:'processing',queue_position:1}, {id:'next',file_name:'next.txt',status:'queued',queue_position:2}]);
assert.ok(elements.trayJobs.innerHTML.indexOf('now.txt') < elements.trayJobs.innerHTML.indexOf('next.txt'));
assert.ok(elements.trayJobs.innerHTML.indexOf('next.txt') < elements.trayJobs.innerHTML.indexOf('later.txt'));
console.log('PASS running analysis first, queued documents in queue order');
